# Stats 701-Homework10 Winter 2018
## Hsuan-Yu Yeh 
### hsuanyu@umich.edu
I discussed with In-Son Tseng and David Li for this homework. For problem 1, I spent 2 hours to finish it. For problem 2, I spent about 8 hours. For problem 3, I spent 2 hours for it. For problem 4, I spent 6 hours for it.

### Problem 1: Constructing a 3-tensor

In [29]:
# Q1

import numpy as np
import tensorflow as tf
# create numpy array first
ary_tall_0 = np.array([ [0, 0, 1], 
                         [0, 0, 1],
                         [0, 0, 1],
                         [1, 1, 1] ])
ary_tall_1 = np.array([ [0, 0, 0], 
                         [0, 0, 0],
                         [0, 0, 1],
                         [0, 0, 0] ])
ary_tall_2 = np.array([ [0, 0, 0], 
                         [0, 0, 0],
                         [0, 1, 1],
                         [0, 0, 0] ])
ary_tall_3 = np.array([ [0, 0, 0], 
                         [0, 0, 0],
                         [0, 0, 1],
                         [0, 0, 0] ])
ary_tall_4 = np.array([ [0, 0, 0], 
                         [0, 0, 0],
                         [0, 0, 1],
                         [0, 0, 0] ])
ary_all = np.array([ary_tall_0, ary_tall_1, ary_tall_2, ary_tall_3, ary_tall_4])

In [30]:
# check the shape
print("The shape of the tensor is:{}".format(ary_all.shape))

The shape of the tensor is:(5, 4, 3)


In [31]:
# check the T
np.sum(ary_all, axis=2)

array([[1, 1, 1, 3],
       [0, 0, 1, 0],
       [0, 0, 2, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0]])

In [32]:
# check the F
np.sum(ary_all, axis=1)

array([[1, 1, 4],
       [0, 0, 1],
       [0, 1, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [34]:
# create a tf constant
tflogo = tf.constant(ary_all)
T_part = tf.reduce_sum(tflogo, axis=2)
F_part = tf.reduce_sum(tflogo, axis=1)

In [35]:
# check the "T" and "F" 
with tf.Session() as sess:
    print("The T:")
    print(sess.run(T_part))
    print("The F:")
    print(sess.run(F_part))

The T:
[[1 1 1 3]
 [0 0 1 0]
 [0 0 2 0]
 [0 0 1 0]
 [0 0 1 0]]
The F:
[[1 1 4]
 [0 0 1]
 [0 1 1]
 [0 0 1]
 [0 0 1]]


### Problem 2: Building and training simple models

In [6]:
# Q2-1
import os
import numpy as np
import tensorflow as tf
os.chdir('/Users/yehhsuan-yu/Umich/Stats701/hsuanyu_hw10')

W = tf.Variable(np.random.randn(6, 1).astype(np.float32))
b = tf.Variable(np.random.randn(1).astype(np.float32))
x = tf.placeholder(dtype=tf.float32, shape=[None, 6])
beta = tf.matmul(x, W) + b

y = tf.placeholder(tf.int64, [None, 1])

hyp = tf.sigmoid(beta)

y_float = tf.cast(y, np.float32)

cost0 = y_float * tf.log(hyp)
cost1 = (1 - y_float) * tf.log(1 - hyp)
cost = (cost0 + cost1)
loss = tf.reduce_sum(-cost)

lr = tf.Variable(1e-3, trainable = False)
train_step = tf.train.GradientDescentOptimizer(lr).minimize(loss)

In [7]:
# Q2-2,3

data_dir = 'logistic_data'
xtrain = np.load(os.path.join(data_dir,'logistic_xtrain.npy'))
xtest = np.load(os.path.join(data_dir,'logistic_xtest.npy'))
ytrain = np.load(os.path.join(data_dir,'logistic_ytrain.npy'))
ytest = np.load(os.path.join(data_dir,'logistic_ytest.npy'))

prediction = tf.cast(tf.round(hyp), tf.int64)
correct_prediction = tf.equal(prediction, y)
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

num_steps = 1000
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    for step in range(num_steps):       
        _, W_, b_, l_, accu_train = sess.run([train_step, W, b, loss, accuracy], feed_dict={x: xtrain, y: ytrain})
        l_test, accu_test = sess.run([loss,accuracy], feed_dict={x: xtest, y: ytest})
        if step % 100 == 0:
            print('Step: {}'.format(step))
            print('W = {}'.format(W_.flatten()))
            print('b = {}'.format(b_.flatten()))
            print('Accuracy:')
            print('   train: {:.6f}'.format(accu_train))
            print('   test: {:.6f}'.format(accu_test))
            print('Loss:')
            print('   train: {:.6f}'.format(l_))
            print('   test: {:.6f}'.format(l_test))

Step: 0
W = [-8.4392422e-01 -8.3498083e-02  8.5094199e-04  1.2234355e+00
  3.0739734e-01  6.8930119e-01]
b = [-0.15905225]
Accuracy:
   train: 0.605500
   test: 0.680000
Loss:
   train: 1318.547607
   test: 304.902893
Step: 100
W = [0.7172959  0.58785075 1.506111   1.9990709  3.2201698  5.255762  ]
b = [-0.6610426]
Accuracy:
   train: 0.846500
   test: 0.866000
Loss:
   train: 704.762756
   test: 170.856323
Step: 200
W = [0.8802521 0.6997496 1.8324376 2.4076731 3.9188828 6.426636 ]
b = [-0.74762684]
Accuracy:
   train: 0.847500
   test: 0.862000
Loss:
   train: 681.255859
   test: 164.300735
Step: 300
W = [0.94165546 0.7451122  1.9801438  2.6111917  4.241353   6.9699187 ]
b = [-0.7899094]
Accuracy:
   train: 0.847500
   test: 0.860000
Loss:
   train: 676.327148
   test: 162.758133
Step: 400
W = [0.97287667 0.7682496  2.0578425  2.7203648  4.4119835  7.2575235 ]
b = [-0.8127134]
Accuracy:
   train: 0.848000
   test: 0.858000
Loss:
   train: 674.957458
   test: 162.254181
Step: 500
W = [

In [8]:
# Q2-4
W0 = tf.placeholder(tf.float32, [None, 7])
W = tf.placeholder(tf.float32, [None, 7])
se = tf.pow(W0-W, 2)


with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(se, feed_dict={W: [[1.0115435, 0.7967201, 2.1544316, 2.8568974, 4.6247444, 7.616026, -0.8414888]], W0: [[1,1,2,3,5,8,-1]]}))

[[1.3325267e-04 4.1322723e-02 2.3849113e-02 2.0478368e-02 1.4081675e-01
  1.4743610e-01 2.5125807e-02]]


In [9]:
# Q2-5,6,8
data_dir = 'normal_data'
xtrain_nm = np.load(os.path.join(data_dir,'normal_xtrain.npy'))
xtest_nm = np.load(os.path.join(data_dir,'normal_xtest.npy'))
ytrain_nm = np.load(os.path.join(data_dir,'normal_ytrain.npy'))
ytest_nm = np.load(os.path.join(data_dir,'normal_ytest.npy'))


x = tf.placeholder(dtype = tf.float32)
y = tf.placeholder(dtype = tf.float32, shape=[None, 3])

mu = tf.Variable(np.zeros(3).astype(np.float32))
sigma = tf.Variable(np.ones(3).astype(np.float32))

xent = 0
negative_log_p = []
for k in range(3):
    negative_log_p.append(tf.log(2 * np.pi * sigma[k]**2) + (x - mu[k])**2 / (sigma[k]**2))
    xent = xent + tf.reduce_mean(y[:, k] * tf.squeeze(negative_log_p[k])) / 2

negative_log_p = tf.concat(negative_log_p, axis=1)
pred = tf.argmin(negative_log_p, axis = 1)
label = tf.argmax(y, axis = 1)
accu = tf.reduce_mean(tf.cast(tf.equal(pred, label), tf.float32))

lr = tf.Variable(1e-1, trainable = False)
train_op = tf.train.AdagradOptimizer(lr).minimize(xent)

saver = tf.train.Saver()

num_steps = 2000
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver = tf.train.Saver()
    for step in range(num_steps):
        _, xent_train, accu_train = sess.run([train_op, xent, accu], feed_dict = {x: xtrain_nm, y: ytrain_nm})
        
        if step % 100 == 0:
            xent_test, accu_test = sess.run([xent, accu], feed_dict = {x: xtest_nm, y: ytest_nm})
            mu_, sigma_ = sess.run([mu, sigma])
            
            print('step: {}'.format(step))
            print('mu = {}'.format(mu_))
            print('var = {}'.format(sigma_**2))
            
            print('Cross entropy:')
            print('  train: {:.6f}'.format(xent_train))
            print('  test: {:.6f}'.format(xent_test))
            
            print('Accuracy:')
            print('  train: {:.6f}'.format(accu_train))
            print('  test: {:.6f}'.format(accu_test))

step: 0
mu = [-0.067883    0.00103171  0.09433642]
var = [1.0832015 1.0010877 1.2086453]
Cross entropy:
  train: 2.908446
  test: 2.459063
Accuracy:
  train: 0.298000
  test: 0.698000
step: 100
mu = [-0.97428054  0.00807605  1.2575095 ]
var = [0.51148903 1.0041908  3.1596632 ]
Cross entropy:
  train: 1.555973
  test: 1.516076
Accuracy:
  train: 0.720500
  test: 0.716000
step: 200
mu = [-0.9809782   0.00807606  1.6943218 ]
var = [0.5114177 1.0041908 3.3215592]
Cross entropy:
  train: 1.492037
  test: 1.457844
Accuracy:
  train: 0.721500
  test: 0.718000
step: 300
mu = [-0.98101026  0.00807606  2.0057266 ]
var = [0.5114177 1.0041908 3.1582181]
Cross entropy:
  train: 1.457420
  test: 1.425922
Accuracy:
  train: 0.723000
  test: 0.716000
step: 400
mu = [-0.98101026  0.00807606  2.2518444 ]
var = [0.5114177 1.0041908 2.8635774]
Cross entropy:
  train: 1.431830
  test: 1.402335
Accuracy:
  train: 0.725000
  test: 0.714000
step: 500
mu = [-0.98101026  0.00807606  2.4528224 ]
var = [0.5114177

In [10]:
# 2-7
param0 = tf.placeholder(tf.float32, [None, 6])
param = tf.placeholder(tf.float32, [None, 6])
sse = tf.reduce_sum(tf.pow(param-param0, 2))


with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(sse, feed_dict={param: [[-0.98101026, 0.00807606, 3.0166788, 0.5114177, 1.0041908, 1.412338]], param0: [[-1, 0, 3, 0.5, 1, 1.5]]}))
    



0.008536565


In [24]:
# save the model for problem 4
mu0 = tf.constant([-1.0], dtype = tf.float32)
mu1 = tf.constant([0.0], dtype = tf.float32)
mu2 = tf.constant([3.0], dtype = tf.float32)
sigma0 = tf.constant([0.5], dtype = tf.float32)
sigma1 = tf.constant([1.0], dtype = tf.float32)
sigma2 = tf.constant([1.5], dtype = tf.float32)
distribnorm = tf.distributions.Normal(loc = [mu0, mu1, mu2], scale = [tf.sqrt(sigma0), tf.sqrt(sigma1), tf.sqrt(sigma2)])
p = distribnorm.prob([x, x, x])
pred = tf.argmax(p)[0]
with tf.Session() as sess:
   print(sess.run(pred, feed_dict = {x: 4.0}))

2


In [25]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    tf.saved_model.simple_save(session = sess,
                              export_dir = '/Users/yehhsuan-yu/Umich/Stats701/hsuanyu_hw10/hsuanyu_normal_trained',
                              inputs = {'x': x},
                              outputs = {'prediction': pred})

INFO:tensorflow:Assets added to graph.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: b'/Users/yehhsuan-yu/Umich/Stats701/hsuanyu_hw10/hsuanyu_normal_trained/saved_model.pb'


### Problem 3: Train the CNN MNIST classifier

In [69]:
# 3 
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data", one_hot=True)

Instructions for updating:
Use the retry module or similar alternatives.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions f

In [70]:
def weight_variable(shape):
  initial = tf.truncated_normal(shape, stddev=0.1)
  return tf.Variable(initial)

def bias_variable(shape):
  initial = tf.constant(0.1, shape=shape)
  return tf.Variable(initial)

def conv2d(x, W):
  return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
  return tf.nn.max_pool(x, ksize=[1, 2, 2, 1],
                        strides=[1, 2, 2, 1], padding='SAME')

In [71]:
# input variables
x_input = tf.placeholder(tf.float32, [None, 784])
y_input = tf.placeholder(tf.float32, [None, 10])
x_img_input = tf.reshape(x_input, [-1, 28, 28, 1])

# dropout setting
keep_prob = tf.placeholder(tf.float32)

# parameters for conv_1
W_conv_1 = weight_variable([5, 5, 1, 32])
b_conv_1 = bias_variable([32])

conv_1 = conv2d(x_img_input, W_conv_1) + b_conv_1
ReLU_1 = tf.nn.relu(conv_1)
pool_1 = max_pool_2x2(ReLU_1)

# parameters for conv_2
W_conv_2 = weight_variable([5, 5, 32, 64])
b_conv_2 = bias_variable([64])

conv_2 = conv2d(pool_1, W_conv_2) + b_conv_2
ReLU_2 = tf.nn.relu(conv_2)
pool_2 = max_pool_2x2(ReLU_2)

reshape = tf.reshape(pool_2, [-1, 7*7*64])

# parameters for fc_1
W_fc_1 = weight_variable([7*7*64, 1024])
b_fc_1 = bias_variable([1024])
fc_1 = tf.matmul(reshape, W_fc_1) + b_fc_1
ReLU_3 = tf.nn.relu(fc_1)
dropout = tf.nn.dropout(ReLU_3, keep_prob)

# parameters for fc_2
W_fc_2 = weight_variable([1024, 10])
b_fc_2 = bias_variable([10])
# output of fc_2
y_logits = tf.matmul(dropout, W_fc_2) + b_fc_2

# loss
cross_entropy = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits(labels=y_input, 
                                            logits=y_logits))
# minimizaer to minimize cross_entropy
obj = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)

# calculate prediction accuracy
correct_prediction = tf.equal(tf.argmax(y_logits, 1), 
                              tf.argmax(y_input, 1)  )
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.



In [72]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(1001):
        batch_img, batch_label = mnist.train.next_batch(100)
        sess.run(obj, feed_dict={x_input: batch_img, 
                                 y_input: batch_label, 
                                 keep_prob: 0.5} )
        if i % 100 == 0:
            test_accuracy = sess.run(accuracy, feed_dict={x_input: mnist.test.images, 
                                                           y_input: mnist.test.labels,
                                                           keep_prob: 1})
            print("Step:{}, accuracy:{:.4f}".format(i, test_accuracy))

Step:0, accuracy:0.1051
Step:100, accuracy:0.8888
Step:200, accuracy:0.9280
Step:300, accuracy:0.9417
Step:400, accuracy:0.9499
Step:500, accuracy:0.9546
Step:600, accuracy:0.9584
Step:700, accuracy:0.9650
Step:800, accuracy:0.9660
Step:900, accuracy:0.9694
Step:1000, accuracy:0.9694
